/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html","./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        cream: '#F5F0E8',
        'ahara-orange': '#C8651B',
        // Dashboard - Material You palette
        'primary': '#9a4600',
        'on-primary': '#ffffff',
        'primary-container': '#ff8a3d',
        'on-primary-container': '#682d00',
        'primary-fixed': '#ffdbc9',
        'primary-fixed-dim': '#ffb68d',
        'secondary': '#006e1c',
        'on-secondary': '#ffffff',
        'secondary-container': '#91f78e',
        'on-secondary-container': '#00731e',
        'tertiary': '#7a5900',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d9a000',
        'tertiary-fixed': '#ffdea3',
        'tertiary-fixed-dim': '#fdbc13',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4200',
        'on-tertiary-container': '#523a00',
        'surface': '#fff8f1',
        'on-surface': '#1e1b17',
        'on-surface-variant': '#564338',
        'surface-container': '#f4ede5',
        'surface-container-low': '#f9f3eb',
        'surface-container-high': '#eee7df',
        'surface-container-highest': '#e8e1da',
        'surface-variant': '#e8e1da',
        'surface-bright': '#fff8f1',
        'surface-dim': '#dfd9d1',
        'background': '#fff8f1',
        'on-background': '#1e1b17',
        'outline': '#8a7266',
        'outline-variant': '#ddc1b3',
        'inverse-primary': '#ffb68d',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
      },
      spacing: {
        'xs': '4px', 'sm': '12px', 'md': '24px', 'lg': '48px', 'xl': '80px',
        'gutter': '20px', 'container-margin': '24px', 'base': '8px',
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}